trigger:
- main

stages:
- stage: Test

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: Test
    displayName: 'Run a one-line script'

    steps:
    - script: echo Hello, world!

- stage: Deploy
  dependsOn: Test

  pool:
    vmImage: windows-2019

  jobs:
  - job: Powershell

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"'
