trigger:
- main

stages:
- stage: Test

variables:
- name: test-var
value: 'Test-Value'

  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: Test
    displayName: 'Run a one-line script'

    steps:
    - script: echo Hello, world! This is variable ===> $(test-var)

- stage: Deploy
  dependsOn: Test

  pool:
    vmImage: windows-2019

  jobs:
  - job: Powershell

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"  Variable ===> $(test-var)'
